language: perl
sudo: false

install:
  - perlbrew list
  - ./maint/travis-dzil nop
  - ./maint/travis-install-deps
  - echo $INSTALL_OPTIONAL | cpanm -n

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - ./maint/travis-run-test
  - perl maint/ci-test-plugins.pl

cache:
  directories:
    - $HOME/mylib

env:
  global:
    - ALIEN_BASE_NO_ABMB=1
  matrix:
    - INSTALL_OPTIONAL="File::Listing File::Listing::Ftpcopy HTML::LinkExtor HTTP::Tiny LWP PkgConfig PkgConfig::LibPkgConf Sort::Versions URI YAML Env::ShellWords Archive::Tar Archive::Zip Devel::Hide"
    - INSTALL_OPTIONAL=""

