name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        cip:
          - alien_build_install_extra: 1
            tag: "5.37"
          - alien_build_install_extra: 1
            env: ALIEN_BUILD_LIVE_TEST=1
            tag: "5.36-alpine3.16"
          - alien_build_install_extra: 1
            env: ALIEN_BUILD_LIVE_TEST=1
            tag: "5.36-bionic"
          - alien_build_install_extra: 1
            env: ALIEN_BUILD_LIVE_TEST=1
            tag: "5.36-centos7"
          - alien_build_install_extra: 1
            env: ALIEN_BUILD_LIVE_TEST=1
            tag: "5.36-fedora36"
          - alien_build_install_extra: 0
            env: ALIEN_BUILD_LIVE_TEST=0
            tag: "5.36-bullseye"
          - alien_build_install_extra: 1
            env: ALIEN_BUILD_LIVE_TEST=1
            tag: "5.36-bullseye"
          - alien_build_install_extra: 1
            env: ALIEN_DOWNLOAD_RULE=digest
            tag: "5.34"
          - alien_build_install_extra: 1
            env: ALIEN_DOWNLOAD_RULE=encrypt
            tag: "5.34"
          - alien_build_install_extra: 1
            env: ALIEN_DOWNLOAD_RULE=digest_or_encrypt
            tag: "5.34"
          - alien_build_install_extra: 1
            env: ALIEN_DOWNLOAD_RULE=digest_and_encrypt
            tag: "5.34"
          - alien_build_install_extra: 1
            tag: "5.36"
          - alien_build_install_extra: 1
            tag: "5.34"
          - alien_build_install_extra: 1
            tag: "5.32"
          - alien_build_install_extra: 1
            tag: "5.30"
          - alien_build_install_extra: 1
            tag: "5.28"
          - alien_build_install_extra: 1
            tag: "5.26"
          - alien_build_install_extra: 1
            tag: "5.24"
          - alien_build_install_extra: 1
            tag: "5.22"
          - alien_build_install_extra: 1
            tag: "5.20"
          - alien_build_install_extra: 0
            tag: "5.18"
          - alien_build_install_extra: 0
            tag: "5.16"
          - alien_build_install_extra: 0
            tag: "5.14"
          - alien_build_install_extra: 0
            tag: "5.12"
          - alien_build_install_extra: 0
            tag: "5.10.1"
          - alien_build_install_extra: 0
            tag: "5.10.0"
          - alien_build_install_extra: 0
            tag: "5.8.8"
          - alien_build_install_extra: 0
            tag: "5.8.4"

    env:
      ALIEN_BUILD_INSTALL_EXTRA: ${{ matrix.cip.alien_build_install_extra }}
      CIP_ENV: ${{ matrix.cip.env }}
      CIP_TAG: ${{ matrix.cip.tag }}


    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap CIP
        run: |
          curl -L https://raw.githubusercontent.com/uperl/cip/main/bin/github-bootstrap | bash

      - name: Cache-Key
        id: cache-key
        run: |
          echo -n '::set-output name=key::'
          cip cache-key

      - name: Cache CPAN modules
        uses: actions/cache@v2
        with:
          path: ~/.cip
          key: ${{ runner.os }}-build-${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-build-${{ steps.cache-key.outputs.key }}

      - name: Start-Container
        run: |
          cip start

      - name: Diagnostics
        run: |
          cip diag

      - name: Install-Dependencies
        run: |
          cip install

      - name: Build + Test
        run: |
          cip script

      - name: Test Plugins
        run: |
          ./maint/cip-test-plugins

      - name: CPAN log
        if: ${{ failure() }}
        run: |
          cat ~/.cpanm/latest-build/build.log
